### ISSUE TITLE
2 small sophistications

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [lachhebo/corona-tracker#1]
Hi @lachhebo !

First of all I would like to thanks for this plugin! It has almost alll the information and settings what the subject needs.

But would like to suggest 2 small sophistications:

1. Please sort in ABC the country list in the drop down as currently the 'random' sorting is very hard to use.
2. Please use one icon for the extension itself on the Gnome panel instead of Covid-19 name as it's a little bit too long and visually off between the further icons. For example there is one simply usable for it: https://materialdesignicons.com/icon/virus

Thanks for your efforts!

**Comment by lachhebo** [comment]
Hi @Tamas-Toth-ebola 

Thank you for kind remarks and your suggestions. I agree those modifications would improve the extensions. 
I would like to implement them but I am a bit overwhelmed currently. Could you help me by forking the project, reordering the list in the (file)[https://github.com/lachhebo/corona-tracker/blob/master/schemas/org.gnome.shell.extensions.corona-tracker.gschema.xml]

**Comment by lachhebo** [comment]
Hi @Tamas-Toth-ebola

Thank you for kind remarks and your suggestions. I agree, those modifications would improve the extensions.
I would like to implement them but I am a bit overwhelmed currently. Could you help me by forking the project, reordering the list in this [file](https://github.com/lachhebo/corona-tracker/blob/master/schemas/org.gnome.shell.extensions.corona-tracker.gschema.xml) and create a pull request. 
It would be amazing.

**Comment by Tamas-Toth-ebola** [comment]
Thanks you for your answer! Sadly my problem that I'm not a real developer so it would be more then acceptable when I could 'solve' these ideas. But nothing is impossible, so if anytime I will have time for it maybe I could dive deeply into your code, but sadly it will be not in the coming weeks I'm sure:(

Of course I'm understanding your answer so just take your time for your more important tasks in your life!
