### ISSUE TITLE
[ Feature request ] Deaths per million

### ISSUE THREAD

**Issue by quasipedia** [lachhebo/corona-tracker#5]
The API has that field, but it is not shown in the extension.

With widely varying level of testing between countries, cases / 1M inhabitants it's almost irrelevant (it's not that death/M is perfect, but at least between countries with similar standards for attribution (e.g.: EU), it works better.

**Comment by lachhebo** [comment]
i have added it in the list of stats; it should be available in a few days in the gnome extension website.

Have a nice evening, stay safe.
