### ISSUE TITLE
undefined values for Poland

### ISSUE THREAD

**Issue by Pioxis** [lachhebo/corona-tracker#6]
Hello, after last upgrade I have problem with data for my country: Poland.
![Zrzut ekranu z 2020-04-17 10-12-10](https://user-images.githubusercontent.com/12051229/79547539-5b177300-8094-11ea-8a0f-cc0e516f92c1.png)

**Comment by lachhebo** [comment]
Thanks for the report, 

The bug occured because v1 of the API has been deprecated in favor of v2, i updated the code to use v2 instead of v1, it shoud land on gnome-extensions in the few next days. 

Stay safe.
